In [91]:
import numpy as np
import pandas as pd
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
plotly.tools.set_credentials_file(username='iremoze', api_key='e1mtSRLLIa1q9JIAqOGz')

In [92]:
df = pd.read_excel("copy.xlsx")
df.head()

,Date/time occurrence,End devices,Malicious code,Respnse,Type of malware,Details
0,2017-01-02 07:58:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80)
1,2017-01-03 07:57:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80)
2,2017-01-03 08:02:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80)
3,2017-01-03 10:16:00,2f,Defo.A,none,virus,MBR (0x80)
4,2017-01-03 16:30:00,2f,Defo.A,none,virus,MBR (0x80)

In [93]:
df['new_date'] = [d.date() for d in df['Date/time occurrence']]
df.head(10)

,Date/time occurrence,End devices,Malicious code,Respnse,Type of malware,Details,new_date
0,2017-01-02 07:58:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-02
1,2017-01-03 07:57:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-03
2,2017-01-03 08:02:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-03
3,2017-01-03 10:16:00,2f,Defo.A,none,virus,MBR (0x80),2017-01-03
4,2017-01-03 16:30:00,2f,Defo.A,none,virus,MBR (0x80),2017-01-03
5,2017-01-04 08:29:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-04
6,2017-01-05 07:58:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-05
7,2017-01-06 07:56:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-06
8,2017-01-07 08:03:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-07
9,2017-01-09 08:06:00,과장님컴퓨터,Defo.A,none,virus,MBR (0x80),2017-01-09

In [94]:
#attachk count in same day
df['freq'] = df.groupby('new_date')['new_date'].transform('count')

In [95]:
#df['ss']= ['Respnse'].value_counts()['none']

In [96]:
#df['vir'] = df.Respnse == 'none'

#df['a'] = df.groupby('new_date')['vir'==True].transform('count')
#df16=df['vir']
#df16 = pd.DataFrame(columns = ['nationality'])
#df16=df['vir']
#df16.keys

In [97]:

# Create random data with numpy
# Create a trace
trace = go.Scatter(
    x = df['new_date'],
    y = df['freq']
)

data = [trace]

py.iplot(data, filename='basic-line')

In [98]:
df2 = df[ (df['Type of malware'] == 'email attachment')]
df2
df2.groupby(['Type of malware','Respnse']).count()
#df['freq'] = df.groupby('new_date')['new_date'].transform('count')
#df2['freq2']= df2.groupby('Respnse')['Respnse'].transform('count')

                            Date/time occurrence  End devices  Malicious code  \
Type of malware  Respnse
email attachment deleted                     355          355              83
                 none                          9            9               9
                 recovered                     8            8               6

                            Details  new_date  freq
Type of malware  Respnse
email attachment deleted        355       355   355
                 none             9         9     9
                 recovered        8         8     8

In [128]:
df3 = df2.groupby(['new_date','Respnse']).size().sort_values(ascending=False) \
  .reset_index(name='Sum')

#deleted  == df4
df4 =df3[(df3['Respnse'] == 'deleted')].sort_values(by='new_date')
#none == df5
df5= df3[(df3['Respnse'] == 'none')].sort_values(by='new_date')
#recovered == df6
df6 = df3[(df3['Respnse'] == 'recovered')].sort_values(by=('new_date'))

      new_date    Respnse  Sum
61  2017-02-16  recovered    1
49  2017-04-27  recovered    2
55  2017-07-20  recovered    2
87  2017-08-24  recovered    1
86  2017-08-28  recovered    1
85  2017-08-30  recovered    1

In [122]:
trace = go.Scatter(
    x = df4['new_date'],
    y = df4['Sum']
)

data = [trace]

py.iplot(data, filename='basic-line')

In [ ]:
#count items based on another column pandas

In [132]:
trace0 = go.Scatter(
    x = df4['new_date'],
    y = df4['Sum'],
    mode = 'lines',
    name = 'deleted'
)
trace1 = go.Scatter(
    x = df4['new_date'],
    y = df5['Sum'],
    mode = 'lines+markers',
    name = 'none'
)
trace2 = go.Scatter(
    x = df4['new_date'],
    y = df6['Sum'],
    mode = 'lines',
    name = 'recovered'
)

data = [trace0, trace1, trace2]

py.iplot(data, filename='scatter-mode')